name: Release to Docker

on:
  push:
    branches:
      - 'release/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Calculate version
        id: spell
        uses: actoaps/version-spell@v3

      - name: Set up JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: 13.0.1

      - name: Gradle Build
        run: |
          ./gradlew clean build

      - name: Release to Docker
        run: |
          docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD

          docker build -t actoaps/web-dispatcher:$BUILD_ID .

          docker tag actoaps/web-dispatcher:$BUILD_ID actoaps/web-dispatcher:latest

          docker push actoaps/web-dispatcher:$BUILD_ID
          docker push actoaps/web-dispatcher:latest
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
          BUILD_ID: ${{ steps.spell.outputs.version }}
